const quizArray = [
  {
    option: "Football",
    quiz: "Quel est le dernier ballon d'or ?",
    vrai: "Karim Benzema",
    faux1: "Lionel Messi",
    faux2: "Kylian MBAPPE",
  },
  {
    option: "Football",
    quiz: "Combien faut-il de zéros pour écrire en chiffres cinquante millions ?",
    vrai: "7",
    faux1: "6",
    faux2: "8",
  },
  {
    option: "Football",
    quiz: "Quel est le plus grand pays du monde ?",
    vrai: "la Russie",
    faux1: "les Etats-unis",
    faux2: "la Chine",
  },
  {
    option: "Football",
    quiz: "Combien de films compte la saga du Seigneur des anneaux de Peter Jackson ?",
    vrai: "3 Films",
    faux1: "4 Films",
    faux2: "5 Films",
  },
  {
    option: "Football",
    quiz: "Quelles ont été les premières paroles de Neil Armstrong quand il a mis un pied sur la Lune en 1969 ?",
    vrai: "C'est un petit pas pour un homme, un bond de geant pour l'humanité",
    faux1:
      "La premiere fois que j'ai regardé la terre, debout sur la lune, j'ai pleuré",
    faux2:
      "De l'autre coté de la mere de l'espace, les etoiles sont d'autres soleils",
  },
  {
    option: "Football",
    quiz: "Dans quel océan navigue-t-on au large de la ville de New York ?",
    vrai: "Océan Atlantique",
    faux1: "Océan Pacifique",
    faux2: "Océan Indien",
  },
  {
    option: "Football",
    quiz: "Quel animal accompagne Harry Potter dans la saga du même nom ?",
    vrai: "Un Hibou",
    faux1: "Un Chat",
    faux2: "Un Chien",
  },
  {
    option: "Football",
    quiz: "Complétez est le nom de la série Netflix tournée à Paris : _____ in Paris.",
    vrai: "Emily",
    faux1: "Melanie",
    faux2: "Julia",
  },
  {
    option: "Football",
    quiz: "Quel le nom donné au symbole du judaïsme ?",
    vrai: "L'étoile de David",
    faux1: "L'étoile de Jesus",
    faux2: "L'étoile d'Abraham",
  },
  {
    option: "Football",
    quiz: "Quel fleuve est commun à la France et à l'Allemagne ?",
    vrai: "Le Rhin",
    faux1: "Le Rhone",
    faux2: "la loire",
  },
  {
    option: "Football",
    quiz: "Comment s'appelle le dieu grec de la mer ?",
    vrai: "Posséidon",
    faux1: "Zeus",
    faux2: "Arès",
  },
  {
    option: "Football",
    quiz: "Sur quoi reposent principalement les travaux des scientifiques Pierre et Marie Curie ?",
    vrai: "La radioactivité",
    faux1: "La Bombe Atomique",
    faux2: "L'électricité",
  },
  {
    option: "Football",
    quiz: "Qu'est-ce que l'hexakosioihexekontahexaphobie ?",
    vrai: "La peur du nombre 666",
    faux1: "La peur des Clowns",
    faux2: "La peur des Requins",
  },
  {
    option: "Football",
    quiz: "Dans quel sport peut-on faire un spare ou bien encore un strike ?",
    vrai: "Le Bowling",
    faux1: "Le BaskettBall",
    faux2: "Le Patinage Artistique",
  },
  {
    option: "Football",
    quiz: "Quelle actrice incarne Erin Brockovich dans un film de 2000 ?",
    vrai: "Julia Roberts",
    faux1: "Sandra Bullok",
    faux2: "Anjelina Jolie",
  },
  {
    option: "Football",
    quiz: "A quelle exclamation est associé le principe d'Archimède ?",
    vrai: "Ereuka",
    faux1: "Bingo!",
    faux2: "Nom de Zeus !",
  },
  {
    option: "Football",
    quiz: "Quel nom d'oiseau utilise-t-on pour désigner un auteur de lettres anonymes ?",
    vrai: "Un Corbeau",
    faux1: "Un pigeon",
    faux2: "Un Perroquet",
  },
  {
    option: "Football",
    quiz: "Quel est le meilleur joueur de Football de l'histoir ?",
    vrai: "Cristiano Ronaldo",
    faux1: "Lionel Messi",
    faux2: "Pele",
  },
  {
    option: "Football",
    quiz: "Au cinéma, quel est le prénom du père de la famille Tuches ?",
    vrai: "jeff",
    faux1: "Hervé",
    faux2: "Germain",
  },
  {
    option: "Football",
    quiz: "Quel est le résultat de cette opération : 2³+1 ?",
    vrai: "9",
    faux1: "27",
    faux2: "7",
  },
];
